apiVersion: batch/v1
kind: Job
metadata:
  name: spe-project-job
spec:
  template:
    metadata:
      labels:
        app: spe-project
    spec:
      containers:
      - name: spe-project
        image: us-west1-docker.pkg.dev/spe-project-449411/quickstart-docker-repo/spe:v2
        args: ["python", "main.py", "run", "-s", "10", "-a", "5", "-u", "8", "10", "-t", "10", "-k", "4"]
        volumeMounts:
        - mountPath: "/app/data"
          name: spe-volume
      volumes:
      - name: spe-volume
        persistentVolumeClaim:
          claimName: spe-pvc
      restartPolicy: Never
  backoffLimit: 4