apiVersion: v1
kind: Pod
metadata:
  name: temp-pod
spec:
  containers:
  - name: temp-container
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - mountPath: "/app/data"
      name: spe-volume
  volumes:
  - name: spe-volume
    persistentVolumeClaim:
      claimName: spe-pvc
  restartPolicy: Never